"""PDF report generation using ReportLab."""
import base64
from io import BytesIO
from datetime import datetime as dt

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
    PageBreak,
)
from reportlab.pdfgen.canvas import Canvas as BaseCanvas

# Colour palette
BLUE_ACCENT = colors.HexColor("#1e40af")
HEADER_BG = colors.HexColor("#f0f4ff")
GRID_LINE = colors.HexColor("#e5e7eb")
WARNING_BG = colors.HexColor("#fef3c7")
WARNING_BORDER = colors.HexColor("#f59e0b")

# Reference display names
REFERENCE_NAMES = {
    "uk-who": "UK-WHO",
    "turners-syndrome": "Turner Syndrome",
    "trisomy-21": "Trisomy 21",
    "cdc": "CDC (US)",
}

# Disclaimer text
DISCLAIMER_TEXT = (
    "This report is generated by the Paediatric Growth Parameters Calculator "
    "for clinical decision support only. It does not constitute a clinical diagnosis. "
    "All growth parameters are derived from validated RCPCH reference data. "
    "Clinicians should exercise professional judgement when interpreting results. "
    "No patient-identifiable information is stored by this application."
)


class NumberedCanvas(BaseCanvas):
    """Canvas subclass that draws 'Page X of Y' footers using two-pass technique."""

    def __init__(self, *args, **kwargs):
        BaseCanvas.__init__(self, *args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        BaseCanvas.showPage(self)

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.setFont("Helvetica", 8)
            self.setFillColor(colors.grey)
            self.drawRightString(
                A4[0] - 2 * cm, 1.2 * cm, f"Page {self._pageNumber} of {num_pages}"
            )
            BaseCanvas.showPage(self)
        BaseCanvas.save(self)


class GrowthReportPDF:
    """Generates a PDF growth parameters report.

    Args:
        results: Calculation results dict from /calculate endpoint.
        patient_info: Dict with sex, birth_date, measurement_date, reference.
        chart_images: Optional dict mapping chart name to base64 data URL strings.
    """

    def __init__(self, results, patient_info, chart_images=None):
        self.results = results
        self.patient_info = patient_info
        self.chart_images = chart_images or {}
        self._init_styles()

    def _init_styles(self):
        """Initialise paragraph styles."""
        self.styles = getSampleStyleSheet()

        self.styles.add(
            ParagraphStyle(
                "ReportTitle",
                parent=self.styles["Heading1"],
                fontName="Helvetica-Bold",
                fontSize=18,
                textColor=BLUE_ACCENT,
                spaceAfter=6,
            )
        )

        self.styles.add(
            ParagraphStyle(
                "SectionTitle",
                parent=self.styles["Heading2"],
                fontName="Helvetica-Bold",
                fontSize=12,
                textColor=BLUE_ACCENT,
                spaceBefore=12,
                spaceAfter=6,
            )
        )

        self.styles.add(
            ParagraphStyle(
                "Disclaimer",
                parent=self.styles["Normal"],
                fontName="Helvetica",
                fontSize=8,
                textColor=colors.grey,
                spaceBefore=12,
            )
        )

        self.styles.add(
            ParagraphStyle(
                "WarningText",
                parent=self.styles["Normal"],
                fontName="Helvetica-Bold",
                fontSize=10,
                textColor=colors.HexColor("#92400e"),
                spaceBefore=2,
                spaceAfter=2,
            )
        )

        self.styles.add(
            ParagraphStyle(
                "BulletItem",
                parent=self.styles["Normal"],
                fontName="Helvetica",
                fontSize=10,
                leftIndent=12,
                spaceBefore=2,
                spaceAfter=2,
            )
        )

        self.styles.add(
            ParagraphStyle(
                "SubInfo",
                parent=self.styles["Normal"],
                fontName="Helvetica",
                fontSize=9,
                textColor=colors.HexColor("#6b7280"),
                spaceAfter=2,
            )
        )

    def generate(self):
        """Build the PDF and return a BytesIO buffer.

        Returns:
            BytesIO: Buffer containing the generated PDF, seeked to position 0.
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            leftMargin=2 * cm,
            rightMargin=2 * cm,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        story = []
        self._add_header(story)
        self._add_patient_info(story)
        self._add_measurements_table(story)
        self._add_additional_parameters(story)
        self._add_warnings(story)
        self._add_chart_images(story)
        self._add_previous_measurements(story)
        self._add_disclaimer(story)

        doc.build(story, canvasmaker=NumberedCanvas)
        buffer.seek(0)
        return buffer

    def _add_header(self, story):
        """Add report title and generation metadata."""
        story.append(Paragraph("GROWTH PARAMETERS REPORT", self.styles["ReportTitle"]))

        now = dt.now().strftime("%d/%m/%Y %H:%M")
        ref_key = self.patient_info.get("reference", "uk-who")
        ref_name = REFERENCE_NAMES.get(ref_key, ref_key)
        story.append(
            Paragraph(
                f"Generated: {now} &nbsp;&nbsp;|&nbsp;&nbsp; Reference: {ref_name}",
                self.styles["SubInfo"],
            )
        )
        story.append(Spacer(1, 12))

    def _add_patient_info(self, story):
        """Add patient demographics section."""
        story.append(Paragraph("Patient Information", self.styles["SectionTitle"]))

        sex = self.patient_info.get("sex", "").capitalize()
        birth_date = self._format_date(self.patient_info.get("birth_date", ""))
        measurement_date = self._format_date(
            self.patient_info.get("measurement_date", "")
        )

        age_cal = self.results.get("age_calendar", {})
        age_str = self._format_calendar_age(age_cal)
        age_decimal = self.results.get("age_years", "")

        info_lines = [
            f"<b>Sex:</b> {sex}",
            f"<b>Date of birth:</b> {birth_date}",
            f"<b>Measurement date:</b> {measurement_date}",
            f"<b>Age:</b> {age_str} ({age_decimal:.2f} years)"
            if isinstance(age_decimal, (int, float))
            else f"<b>Age:</b> {age_str}",
        ]

        if self.results.get("gestation_correction_applied"):
            corrected_cal = self.results.get("corrected_age_calendar", {})
            corrected_dec = self.results.get("corrected_age_years", "")
            corrected_str = self._format_calendar_age(corrected_cal)
            if corrected_str:
                info_lines.append(
                    f"<b>Corrected age:</b> {corrected_str} ({corrected_dec:.2f} years)"
                    if isinstance(corrected_dec, (int, float))
                    else f"<b>Corrected age:</b> {corrected_str}"
                )

        for line in info_lines:
            story.append(Paragraph(line, self.styles["Normal"]))
        story.append(Spacer(1, 8))

    def _add_measurements_table(self, story):
        """Add table of current measurements with centile and SDS."""
        measurements = []
        for key, label, unit in [
            ("weight", "Weight", "kg"),
            ("height", "Height", "cm"),
            ("bmi", "BMI", "kg/m\u00b2"),
            ("ofc", "OFC", "cm"),
        ]:
            m = self.results.get(key)
            if m and isinstance(m, dict):
                value = m.get("value", "")
                centile = self._fmt_centile(m.get("centile"))
                sds = self._fmt_sds(m.get("sds"))
                measurements.append((label, f"{value} {unit}", centile, sds))

        if not measurements:
            return

        story.append(Paragraph("Current Measurements", self.styles["SectionTitle"]))

        header = ["Parameter", "Value", "Centile", "SDS"]
        data = [header] + list(measurements)

        col_widths = [4.5 * cm, 4.5 * cm, 4 * cm, 4 * cm]
        table = Table(data, colWidths=col_widths)
        table.setStyle(
            TableStyle(
                [
                    # Header row
                    ("BACKGROUND", (0, 0), (-1, 0), HEADER_BG),
                    ("TEXTCOLOR", (0, 0), (-1, 0), BLUE_ACCENT),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, 0), 10),
                    # Data rows
                    ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 1), (-1, -1), 10),
                    # Grid
                    ("GRID", (0, 0), (-1, -1), 0.5, GRID_LINE),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#fafafa")]),
                    # Alignment
                    ("ALIGN", (1, 0), (-1, -1), "CENTRE"),
                    ("ALIGN", (0, 0), (0, -1), "LEFT"),
                    # Padding
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )
        story.append(table)
        story.append(Spacer(1, 8))

    def _add_additional_parameters(self, story):
        """Add bullet list of additional calculated parameters."""
        items = []

        # BSA
        bsa = self.results.get("bsa")
        if bsa and isinstance(bsa, dict):
            items.append(
                f"\u2022 <b>BSA:</b> {bsa['value']} m\u00b2 ({bsa['method']} method)"
            )

        # BMI percentage median
        bmi = self.results.get("bmi")
        if bmi and isinstance(bmi, dict) and bmi.get("percentage_median") is not None:
            items.append(
                f"\u2022 <b>BMI % of median:</b> {bmi['percentage_median']}%"
            )

        # Height velocity
        hv = self.results.get("height_velocity")
        if hv and isinstance(hv, dict) and hv.get("value") is not None:
            vel = self._fmt_value(hv["value"], 1)
            based_on = hv.get("based_on_date", "")
            suffix = f" (based on measurement from {self._format_date(based_on)})" if based_on else ""
            items.append(
                f"\u2022 <b>Height velocity:</b> {vel} cm/year{suffix}"
            )

        # Mid-parental height
        mph = self.results.get("mid_parental_height")
        if mph and isinstance(mph, dict):
            mph_val = self._fmt_value(mph.get("mid_parental_height"), 1)
            lower = self._fmt_value(mph.get("target_range_lower"), 1)
            upper = self._fmt_value(mph.get("target_range_upper"), 1)
            centile = self._fmt_centile(mph.get("mid_parental_height_centile"))
            sds = self._fmt_sds(mph.get("mid_parental_height_sds"))
            items.append(
                f"\u2022 <b>Mid-parental height:</b> {mph_val} cm "
                f"(target range {lower}\u2013{upper} cm, "
                f"centile {centile}, SDS {sds})"
            )

        # Bone age
        ba = self.results.get("bone_age_height")
        if ba and isinstance(ba, dict):
            ba_val = self._fmt_value(ba.get("bone_age"), 1)
            ba_std_code = ba.get("standard", "gp")
            ba_std = "Greulich-Pyle" if ba_std_code == "gp" else "TW3"
            ba_centile = self._fmt_centile(ba.get("centile"))
            ba_sds = self._fmt_sds(ba.get("sds"))
            items.append(
                f"\u2022 <b>Bone age:</b> {ba_val} years ({ba_std}) \u2014 "
                f"height for bone age: centile {ba_centile}, SDS {ba_sds}"
            )

        # GH dose
        gh = self.results.get("gh_dose")
        if gh and isinstance(gh, dict):
            daily = gh.get("initial_daily_dose")
            if daily is not None:
                daily_str = self._fmt_value(daily, 1)
                weekly_str = self._fmt_value(daily * 7, 1)
                items.append(
                    f"\u2022 <b>GH initial dose:</b> {daily_str} mg/day ({weekly_str} mg/week)"
                )

        if not items:
            return

        story.append(
            Paragraph("Additional Parameters", self.styles["SectionTitle"])
        )
        for item in items:
            story.append(Paragraph(item, self.styles["BulletItem"]))
        story.append(Spacer(1, 8))

    def _add_warnings(self, story):
        """Add validation warning messages if present."""
        messages = self.results.get("validation_messages", [])
        if not messages:
            return

        story.append(Paragraph("Warnings", self.styles["SectionTitle"]))

        for msg in messages:
            # Warning symbol + message
            story.append(
                Paragraph(f"\u26a0 {msg}", self.styles["WarningText"])
            )
        story.append(Spacer(1, 8))

    def _add_chart_images(self, story):
        """Decode base64 data URL chart images and embed in PDF."""
        if not self.chart_images:
            return

        story.append(Paragraph("Growth Charts", self.styles["SectionTitle"]))

        for chart_name, data_url in self.chart_images.items():
            try:
                # Parse data URL: "data:image/png;base64,..."
                if "," in data_url:
                    encoded = data_url.split(",", 1)[1]
                else:
                    encoded = data_url

                image_bytes = base64.b64decode(encoded)
                image_buffer = BytesIO(image_bytes)

                img = Image(
                    image_buffer,
                    width=15 * cm,
                    height=10 * cm,
                    kind="proportional",
                )
                label = chart_name.replace("_", " ").capitalize()
                story.append(Paragraph(f"<b>{label}</b>", self.styles["Normal"]))
                story.append(Spacer(1, 4))
                story.append(img)
                story.append(Spacer(1, 12))
            except Exception:
                # Skip charts that fail to decode
                continue

    def _add_previous_measurements(self, story):
        """Add previous measurements table on a new page."""
        prev = self.results.get("previous_measurements")
        if not prev or not isinstance(prev, list):
            return

        story.append(PageBreak())
        story.append(
            Paragraph("Previous Measurements", self.styles["SectionTitle"])
        )

        # Build table data
        header = ["Date", "Age (years)", "Height (cm)", "Ht Centile", "Weight (kg)", "Wt Centile"]
        data = [header]

        for entry in prev:
            date_str = self._format_date(entry.get("date", ""))
            age = entry.get("age", "")
            if isinstance(age, (int, float)):
                age = f"{age:.2f}"

            ht = entry.get("height", {})
            ht_val = self._fmt_value(ht.get("value"), 1) if isinstance(ht, dict) else ""
            ht_centile = self._fmt_centile(ht.get("centile")) if isinstance(ht, dict) else ""

            wt = entry.get("weight", {})
            wt_val = self._fmt_value(wt.get("value"), 1) if isinstance(wt, dict) else ""
            wt_centile = self._fmt_centile(wt.get("centile")) if isinstance(wt, dict) else ""

            data.append([date_str, age, ht_val, ht_centile, wt_val, wt_centile])

        col_widths = [2.8 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm, 2.5 * cm]
        table = Table(data, colWidths=col_widths)
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), HEADER_BG),
                    ("TEXTCOLOR", (0, 0), (-1, 0), BLUE_ACCENT),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, 0), 9),
                    ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                    ("FONTSIZE", (0, 1), (-1, -1), 9),
                    ("GRID", (0, 0), (-1, -1), 0.5, GRID_LINE),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#fafafa")]),
                    ("ALIGN", (1, 0), (-1, -1), "CENTRE"),
                    ("ALIGN", (0, 0), (0, -1), "LEFT"),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        story.append(table)
        story.append(Spacer(1, 8))

    def _add_disclaimer(self, story):
        """Add disclaimer text at the end of the report."""
        story.append(Spacer(1, 12))
        story.append(Paragraph(DISCLAIMER_TEXT, self.styles["Disclaimer"]))

    # --- Helpers ---

    @staticmethod
    def _fmt_centile(val):
        """Format centile: 1dp with % suffix. e.g. 46.4%"""
        if val is None or val == "":
            return "N/A"
        return f"{float(val):.1f}%"

    @staticmethod
    def _fmt_sds(val):
        """Format SDS: 2dp with explicit sign. e.g. +0.16 or -0.39"""
        if val is None or val == "":
            return "N/A"
        v = float(val)
        return f"{v:+.2f}"

    @staticmethod
    def _fmt_value(val, dp=1):
        """Format a numeric value to given decimal places."""
        if val is None or val == "":
            return ""
        return f"{float(val):.{dp}f}"

    @staticmethod
    def _format_date(date_str):
        """Convert YYYY-MM-DD to DD/MM/YYYY. Returns original string on failure."""
        try:
            d = dt.strptime(date_str, "%Y-%m-%d")
            return d.strftime("%d/%m/%Y")
        except (ValueError, TypeError):
            return str(date_str)

    @staticmethod
    def _format_calendar_age(age_dict):
        """Format age_calendar dict as human-readable string."""
        if not age_dict:
            return ""
        parts = []
        years = age_dict.get("years", 0)
        months = age_dict.get("months", 0)
        days = age_dict.get("days", 0)
        if years:
            parts.append(f"{years} year{'s' if years != 1 else ''}")
        if months:
            parts.append(f"{months} month{'s' if months != 1 else ''}")
        if days or not parts:
            parts.append(f"{days} day{'s' if days != 1 else ''}")
        return ", ".join(parts)
