let formatResultsAsText;

beforeAll(async () => {
  ({ formatResultsAsText } = await import('../../static/clipboard.mjs'));
});

describe('formatResultsAsText', () => {
  const baseResults = {
    age_years: 3.0,
    age_calendar: { years: 3, months: 0, days: 0 },
    gestation_correction_applied: false,
    weight: { value: 14.5, centile: 50.1, sds: 0.03 },
    height: { value: 96.0, centile: 25.5, sds: -0.67 },
    bmi: { value: 15.7, centile: 75.3, sds: 0.68, percentage_median: 105.2 },
    ofc: { value: 50.0, centile: 45.7, sds: -0.11 },
    validation_messages: [],
  };
  const baseInfo = { sex: 'male', reference: 'uk-who' };

  test('includes header', () => {
    const text = formatResultsAsText(baseResults, baseInfo);
    expect(text).toContain('GROWTH PARAMETERS');
  });

  test('includes age', () => {
    const text = formatResultsAsText(baseResults, baseInfo);
    expect(text).toContain('Age: 3.00 years');
  });

  test('includes reference', () => {
    const text = formatResultsAsText(baseResults, baseInfo);
    expect(text).toContain('Reference: UK-WHO');
  });

  test('includes weight with centile and SDS', () => {
    const text = formatResultsAsText(baseResults, baseInfo);
    expect(text).toContain('Weight: 14.5 kg');
    expect(text).toContain('Centile: 50.1%');
    expect(text).toContain('SDS: +0.03');
  });

  test('includes height', () => {
    const text = formatResultsAsText(baseResults, baseInfo);
    expect(text).toContain('Height: 96.0 cm');
  });

  test('includes BMI with percentage median', () => {
    const text = formatResultsAsText(baseResults, baseInfo);
    expect(text).toContain('BMI: 15.7');
    expect(text).toContain('% Median: 105.2%');
  });

  test('includes OFC', () => {
    const text = formatResultsAsText(baseResults, baseInfo);
    expect(text).toContain('Head Circumference (OFC): 50.0 cm');
  });

  test('includes MPH when present', () => {
    const results = {
      ...baseResults,
      mid_parental_height: { mid_parental_height: 178.0, target_range_lower: 169.5, target_range_upper: 186.5 },
    };
    const text = formatResultsAsText(results, baseInfo);
    expect(text).toContain('Mid-Parental Height: 178.0 cm');
    expect(text).toContain('Target Range: 169.5-186.5 cm');
  });

  test('includes BSA when present', () => {
    const results = { ...baseResults, bsa: { value: 0.62, method: 'Boyd' } };
    const text = formatResultsAsText(results, baseInfo);
    expect(text).toContain('Body Surface Area: 0.62');
    expect(text).toContain('Boyd');
  });

  test('includes height velocity when present', () => {
    const results = { ...baseResults, height_velocity: { value: 6.8 } };
    const text = formatResultsAsText(results, baseInfo);
    expect(text).toContain('Height Velocity: 6.8 cm/year');
  });

  test('includes GH dose with all formats when BSA and weight present', () => {
    const results = { ...baseResults, gh_dose: { initial_daily_dose: 0.6 }, bsa: { value: 0.95, method: 'Boyd' } };
    const info = { ...baseInfo, weight: 25.0 };
    const text = formatResultsAsText(results, info);
    expect(text).toContain('0.6 mg/day');
    expect(text).toContain('mg/m\u00B2/week');
    expect(text).toContain('mcg/kg/day');
  });

  test('includes bone age with chronological age and SDS', () => {
    const results = { ...baseResults, age_years: 8.0, bone_age_height: { bone_age: 7.5, standard: 'gp', sds: 0.15, centile: 56.0, within_window: true, height: 125.0 } };
    const text = formatResultsAsText(results, baseInfo);
    expect(text).toContain('Bone Age: 7.5 years vs chronological age 8.0 years');
    expect(text).toContain('SDS +0.15');
    expect(text).toContain('Greulich-Pyle');
  });

  test('omits missing sections', () => {
    const minimal = {
      age_years: 2.0,
      age_calendar: { years: 2, months: 0, days: 0 },
      weight: { value: 12.0, centile: 40.0, sds: -0.25 },
      validation_messages: [],
    };
    const text = formatResultsAsText(minimal, baseInfo);
    expect(text).not.toContain('Height:');
    expect(text).not.toContain('BMI:');
    expect(text).not.toContain('Mid-Parental Height');
    expect(text).not.toContain('BSA');
  });

  test('includes warnings when present', () => {
    const results = { ...baseResults, validation_messages: ['SDS is very extreme (+4.5 SDS).'] };
    const text = formatResultsAsText(results, baseInfo);
    expect(text).toContain('WARNINGS');
    expect(text).toContain('extreme');
  });

  test('includes footer', () => {
    const text = formatResultsAsText(baseResults, baseInfo);
    expect(text).toContain('Generated by Growth Parameters Calculator');
  });
});
